import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const data = [
  {
    name: "Struktur Data",
    description: "Array, Linked List, Stack, Queue, Tree, Graph",
    quizzes: [
      {
        name: "Array & Kompleksitas Waktu",
        description: "Dasar array, operasi, dan analisis Big-O",
        questions: [
          {
            text: "Apa kompleksitas waktu untuk mengakses elemen pada array berdasarkan index?",
            optionA: "O(n)",
            optionB: "O(log n)",
            optionC: "O(1)",
            optionD: "O(n²)",
            correctAnswer: "C",
            explanation: "Array memiliki akses langsung ke elemen berdasarkan index menggunakan alamat memori, sehingga kompleksitasnya O(1) atau konstan.",
          },
          {
            text: "Apa kelemahan utama array dibandingkan linked list?",
            optionA: "Akses elemen lebih lambat",
            optionB: "Ukurannya bersifat statis/tetap",
            optionC: "Tidak bisa menyimpan data primitif",
            optionD: "Tidak mendukung perulangan",
            correctAnswer: "B",
            explanation: "Array memiliki ukuran tetap saat dideklarasikan, sedangkan linked list bisa tumbuh secara dinamis sesuai kebutuhan.",
          },
          {
            text: "Notasi Big-O manakah yang menggambarkan kompleksitas waktu terbaik (paling efisien)?",
            optionA: "O(n²)",
            optionB: "O(n log n)",
            optionC: "O(n)",
            optionD: "O(1)",
            correctAnswer: "D",
            explanation: "O(1) atau waktu konstan adalah yang paling efisien karena tidak bergantung pada ukuran input.",
          },
          {
            text: "Operasi apa yang memiliki kompleksitas O(n) pada array tidak terurut?",
            optionA: "Akses elemen berdasarkan index",
            optionB: "Pencarian elemen (linear search)",
            optionC: "Mengubah nilai elemen berdasarkan index",
            optionD: "Mengambil elemen pertama",
            correctAnswer: "B",
            explanation: "Pencarian linear pada array tidak terurut harus memeriksa setiap elemen satu per satu, sehingga kompleksitasnya O(n).",
          },
          {
            text: "Jika sebuah algoritma memiliki dua perulangan bersarang yang masing-masing berjalan n kali, berapa kompleksitas waktunya?",
            optionA: "O(n)",
            optionB: "O(2n)",
            optionC: "O(n²)",
            optionD: "O(log n)",
            correctAnswer: "C",
            explanation: "Dua perulangan bersarang yang masing-masing berjalan n kali menghasilkan n × n = n² operasi, sehingga kompleksitasnya O(n²).",
          },
        ],
      },
      {
        name: "Linked List",
        description: "Singly, Doubly, dan Circular Linked List",
        questions: [
          {
            text: "Apa kelebihan utama linked list dibandingkan array?",
            optionA: "Akses elemen lebih cepat",
            optionB: "Penggunaan memori lebih efisien untuk ukuran tetap",
            optionC: "Ukurannya dinamis dan mudah ditambah/dihapus",
            optionD: "Tidak memerlukan pointer",
            correctAnswer: "C",
            explanation: "Linked list bersifat dinamis sehingga dapat bertumbuh dan menyusut sesuai kebutuhan, tidak seperti array yang ukurannya tetap.",
          },
          {
            text: "Pada singly linked list, setiap node terdiri dari?",
            optionA: "Data saja",
            optionB: "Data dan pointer ke node berikutnya",
            optionC: "Data dan pointer ke node sebelumnya",
            optionD: "Data, pointer ke node berikutnya, dan pointer ke node sebelumnya",
            correctAnswer: "B",
            explanation: "Pada singly linked list, setiap node menyimpan data dan satu pointer yang menunjuk ke node berikutnya dalam list.",
          },
          {
            text: "Apa perbedaan utama doubly linked list dari singly linked list?",
            optionA: "Doubly linked list lebih cepat dalam pencarian",
            optionB: "Setiap node pada doubly linked list punya pointer ke node sebelumnya dan berikutnya",
            optionC: "Doubly linked list tidak memiliki node head",
            optionD: "Doubly linked list hanya bisa ditraversal dari belakang",
            correctAnswer: "B",
            explanation: "Doubly linked list memiliki dua pointer per node: satu ke node berikutnya (next) dan satu ke node sebelumnya (prev), memungkinkan traversal dua arah.",
          },
          {
            text: "Kompleksitas waktu untuk menghapus node di awal singly linked list adalah?",
            optionA: "O(n)",
            optionB: "O(log n)",
            optionC: "O(1)",
            optionD: "O(n²)",
            correctAnswer: "C",
            explanation: "Menghapus node di awal linked list hanya memerlukan pembaruan pointer head ke node berikutnya, sehingga kompleksitasnya O(1).",
          },
          {
            text: "Pada circular linked list, pointer next dari node terakhir menunjuk ke?",
            optionA: "NULL",
            optionB: "Node terakhir itu sendiri",
            optionC: "Node pertama (head)",
            optionD: "Node tengah",
            correctAnswer: "C",
            explanation: "Pada circular linked list, node terakhir menunjuk kembali ke node pertama (head), membentuk lingkaran yang tidak ada ujungnya.",
          },
        ],
      },
      {
        name: "Stack & Queue",
        description: "Prinsip LIFO, FIFO, dan implementasinya",
        questions: [
          {
            text: "Struktur data apa yang menggunakan prinsip LIFO (Last In First Out)?",
            optionA: "Queue",
            optionB: "Stack",
            optionC: "Array",
            optionD: "Linked List",
            correctAnswer: "B",
            explanation: "Stack menggunakan prinsip LIFO dimana elemen yang terakhir masuk adalah yang pertama keluar, seperti tumpukan piring.",
          },
          {
            text: "Operasi push pada stack digunakan untuk?",
            optionA: "Menghapus elemen dari atas stack",
            optionB: "Melihat elemen teratas tanpa menghapus",
            optionC: "Menambah elemen ke atas stack",
            optionD: "Mengosongkan stack",
            correctAnswer: "C",
            explanation: "Operasi push menambahkan elemen baru ke bagian atas (top) stack.",
          },
          {
            text: "Struktur data Queue menggunakan prinsip?",
            optionA: "LIFO (Last In First Out)",
            optionB: "FIFO (First In First Out)",
            optionC: "FILO (First In Last Out)",
            optionD: "Random Access",
            correctAnswer: "B",
            explanation: "Queue menggunakan prinsip FIFO dimana elemen yang pertama masuk adalah yang pertama keluar, seperti antrian di kasir.",
          },
          {
            text: "Aplikasi nyata yang paling tepat menggunakan struktur data Stack adalah?",
            optionA: "Sistem antrian tiket",
            optionB: "Daftar putar musik berurutan",
            optionC: "Fitur Undo/Redo pada teks editor",
            optionD: "Penjadwalan proses printer",
            correctAnswer: "C",
            explanation: "Fitur Undo/Redo menggunakan stack karena operasi terakhir yang dilakukan adalah yang pertama di-undo (LIFO).",
          },
          {
            text: "Kondisi Stack Overflow terjadi ketika?",
            optionA: "Stack kosong dan operasi pop dilakukan",
            optionB: "Stack penuh dan operasi push dilakukan",
            optionC: "Stack memiliki satu elemen",
            optionD: "Operasi peek dilakukan pada stack kosong",
            correctAnswer: "B",
            explanation: "Stack overflow terjadi ketika mencoba menambah elemen (push) ke stack yang sudah penuh melebihi kapasitasnya.",
          },
        ],
      },
      {
        name: "Tree & Binary Search Tree",
        description: "Konsep pohon, BST, dan traversal",
        questions: [
          {
            text: "Pada Binary Search Tree (BST), nilai node anak kiri selalu?",
            optionA: "Lebih besar dari node induknya",
            optionB: "Lebih kecil dari node induknya",
            optionC: "Sama dengan node induknya",
            optionD: "Tidak ada aturan khusus",
            correctAnswer: "B",
            explanation: "Pada BST, semua node di subtree kiri memiliki nilai lebih kecil dari node induk, sedangkan subtree kanan memiliki nilai lebih besar.",
          },
          {
            text: "Traversal Inorder pada BST akan menghasilkan data dalam urutan?",
            optionA: "Acak",
            optionB: "Menurun (descending)",
            optionC: "Menaik (ascending)",
            optionD: "Level per level",
            correctAnswer: "C",
            explanation: "Traversal Inorder (Kiri-Root-Kanan) pada BST menghasilkan data dalam urutan menaik karena mengunjungi node kiri (kecil) sebelum root dan kanan (besar).",
          },
          {
            text: "Node yang tidak memiliki anak (child) disebut?",
            optionA: "Root node",
            optionB: "Internal node",
            optionC: "Leaf node",
            optionD: "Parent node",
            correctAnswer: "C",
            explanation: "Leaf node atau node daun adalah node yang tidak memiliki anak sama sekali, berada di ujung cabang pohon.",
          },
          {
            text: "Kompleksitas pencarian pada BST yang seimbang (balanced) adalah?",
            optionA: "O(n)",
            optionB: "O(log n)",
            optionC: "O(1)",
            optionD: "O(n²)",
            correctAnswer: "B",
            explanation: "Pada BST seimbang, setiap langkah pencarian mengeliminasi setengah dari node yang tersisa, menghasilkan kompleksitas O(log n).",
          },
          {
            text: "Apa yang dimaksud dengan Height (tinggi) dari sebuah tree?",
            optionA: "Jumlah total node dalam tree",
            optionB: "Jumlah node pada level terdalam",
            optionC: "Panjang path terpanjang dari root ke leaf",
            optionD: "Jumlah edge dari root ke node tertentu",
            correctAnswer: "C",
            explanation: "Height tree adalah panjang path (jumlah edge) terpanjang dari root ke leaf node yang paling dalam.",
          },
        ],
      },
    ],
  },
  {
    name: "Algoritma",
    description: "Sorting, Searching, Rekursi, Dynamic Programming",
    quizzes: [
      {
        name: "Sorting Algoritma",
        description: "Bubble, Selection, Insertion, Merge, Quick Sort",
        questions: [
          {
            text: "Algoritma sorting apa yang memiliki kompleksitas rata-rata O(n log n)?",
            optionA: "Bubble Sort",
            optionB: "Insertion Sort",
            optionC: "Merge Sort",
            optionD: "Selection Sort",
            correctAnswer: "C",
            explanation: "Merge Sort menggunakan pendekatan divide and conquer dan selalu memiliki kompleksitas O(n log n) di semua kasus.",
          },
          {
            text: "Bubble Sort mendapatkan namanya karena?",
            optionA: "Ditemukan oleh ilmuwan bernama Bubble",
            optionB: "Elemen besar 'menggelembung' ke atas seperti gelembung",
            optionC: "Algoritmanya berbentuk seperti gelembung",
            optionD: "Menggunakan memori berbentuk gelembung",
            correctAnswer: "B",
            explanation: "Bubble Sort dinamai demikian karena elemen-elemen besar secara bertahap 'menggelembung' ke posisi akhir array seperti gelembung naik ke permukaan.",
          },
          {
            text: "Algoritma sorting mana yang paling efisien untuk data yang hampir terurut?",
            optionA: "Quick Sort",
            optionB: "Merge Sort",
            optionC: "Insertion Sort",
            optionD: "Selection Sort",
            correctAnswer: "C",
            explanation: "Insertion Sort sangat efisien untuk data yang hampir terurut karena hanya perlu sedikit pergeseran, mencapai kompleksitas mendekati O(n).",
          },
          {
            text: "Apa kompleksitas waktu terburuk Quick Sort?",
            optionA: "O(n log n)",
            optionB: "O(n)",
            optionC: "O(n²)",
            optionD: "O(log n)",
            correctAnswer: "C",
            explanation: "Quick Sort memiliki kompleksitas terburuk O(n²) ketika pivot yang dipilih selalu elemen terkecil atau terbesar (data sudah terurut).",
          },
          {
            text: "Manakah algoritma sorting yang bersifat stable (mempertahankan urutan relatif elemen yang sama)?",
            optionA: "Quick Sort",
            optionB: "Selection Sort",
            optionC: "Heap Sort",
            optionD: "Merge Sort",
            correctAnswer: "D",
            explanation: "Merge Sort adalah algoritma stable sort karena mempertahankan urutan relatif elemen-elemen dengan nilai yang sama.",
          },
        ],
      },
      {
        name: "Searching & Rekursi",
        description: "Linear Search, Binary Search, dan pemrograman rekursif",
        questions: [
          {
            text: "Binary Search mensyaratkan data harus dalam keadaan?",
            optionA: "Acak",
            optionB: "Terurut",
            optionC: "Duplikat",
            optionD: "Genap jumlahnya",
            correctAnswer: "B",
            explanation: "Binary Search hanya bisa digunakan pada data yang sudah terurut karena algoritma ini membandingkan elemen tengah untuk menentukan ke bagian mana pencarian dilanjutkan.",
          },
          {
            text: "Kompleksitas Binary Search adalah?",
            optionA: "O(n)",
            optionB: "O(n²)",
            optionC: "O(log n)",
            optionD: "O(1)",
            correctAnswer: "C",
            explanation: "Binary Search membagi ruang pencarian menjadi dua setiap langkahnya, sehingga kompleksitasnya O(log n).",
          },
          {
            text: "Apa yang dimaksud dengan base case dalam rekursi?",
            optionA: "Kasus pertama yang diselesaikan",
            optionB: "Kondisi yang menghentikan pemanggilan rekursif",
            optionC: "Fungsi utama yang memanggil rekursi",
            optionD: "Kasus tersulit dalam rekursi",
            correctAnswer: "B",
            explanation: "Base case adalah kondisi yang ketika terpenuhi akan menghentikan pemanggilan fungsi rekursif lebih lanjut, mencegah infinite recursion.",
          },
          {
            text: "Apa risiko utama jika fungsi rekursif tidak memiliki base case?",
            optionA: "Program berjalan lebih lambat",
            optionB: "Hasil selalu salah",
            optionC: "Stack overflow",
            optionD: "Memori heap penuh",
            correctAnswer: "C",
            explanation: "Tanpa base case, fungsi rekursif akan terus memanggil dirinya sendiri tanpa berhenti hingga call stack penuh, menyebabkan stack overflow.",
          },
          {
            text: "Manakah contoh masalah yang paling tepat diselesaikan dengan rekursi?",
            optionA: "Menghitung rata-rata array",
            optionB: "Mengurutkan array dengan bubble sort",
            optionC: "Menghitung faktorial bilangan",
            optionD: "Mencari elemen terbesar dalam array",
            correctAnswer: "C",
            explanation: "Faktorial adalah contoh klasik rekursi karena n! = n × (n-1)!, membentuk struktur yang secara alami rekursif.",
          },
        ],
      },
      {
        name: "Dynamic Programming & Greedy",
        description: "Memoization, tabulation, dan algoritma greedy",
        questions: [
          {
            text: "Apa prinsip utama Dynamic Programming?",
            optionA: "Membagi masalah menjadi submasalah yang independen",
            optionB: "Menyimpan hasil submasalah yang sudah diselesaikan untuk digunakan kembali",
            optionC: "Selalu memilih solusi lokal terbaik",
            optionD: "Menggunakan rekursi tanpa batas",
            correctAnswer: "B",
            explanation: "Dynamic Programming menyimpan (memoize) hasil komputasi submasalah yang sudah diselesaikan untuk menghindari pengulangan kalkulasi yang sama.",
          },
          {
            text: "Apa perbedaan memoization dan tabulation dalam Dynamic Programming?",
            optionA: "Memoization lebih lambat dari tabulation",
            optionB: "Memoization top-down (rekursif), tabulation bottom-up (iteratif)",
            optionC: "Tabulation menggunakan lebih banyak memori",
            optionD: "Tidak ada perbedaan keduanya sama saja",
            correctAnswer: "B",
            explanation: "Memoization adalah pendekatan top-down yang menghitung sesuai kebutuhan, sedangkan tabulation adalah pendekatan bottom-up yang menghitung semua submasalah terlebih dahulu.",
          },
          {
            text: "Algoritma Greedy mengambil keputusan berdasarkan?",
            optionA: "Seluruh kondisi masa depan",
            optionB: "Pilihan optimal secara global",
            optionC: "Pilihan yang tampak terbaik pada saat itu (lokal optimal)",
            optionD: "Hasil percobaan sebelumnya",
            correctAnswer: "C",
            explanation: "Algoritma Greedy selalu memilih opsi yang tampak terbaik pada setiap langkah tanpa mempertimbangkan konsekuensi di masa depan.",
          },
          {
            text: "Masalah Fibonacci adalah contoh klasik Dynamic Programming karena?",
            optionA: "Hasilnya selalu bilangan prima",
            optionB: "Memiliki submasalah yang tumpang tindih (overlapping subproblems)",
            optionC: "Hanya bisa diselesaikan secara rekursif",
            optionD: "Kompleksitasnya selalu O(1)",
            correctAnswer: "B",
            explanation: "Fibonacci memiliki overlapping subproblems karena F(n) = F(n-1) + F(n-2), di mana banyak nilai yang perlu dihitung berulang kali tanpa memoization.",
          },
          {
            text: "Kapan algoritma Greedy menghasilkan solusi optimal?",
            optionA: "Selalu menghasilkan solusi optimal",
            optionB: "Ketika masalah memiliki struktur optimal substruktuf dan greedy choice property",
            optionC: "Hanya untuk masalah sorting",
            optionD: "Ketika data tidak terurut",
            correctAnswer: "B",
            explanation: "Greedy menghasilkan solusi optimal ketika masalah memiliki optimal substructure (solusi optimal terdiri dari solusi optimal submasalah) dan greedy choice property (pilihan lokal optimal selalu mengarah ke solusi global optimal).",
          },
        ],
      },
    ],
  },
  {
    name: "Basis Data",
    description: "SQL, Normalisasi, ERD, Transaksi, Indexing",
    quizzes: [
      {
        name: "Dasar SQL",
        description: "SELECT, INSERT, UPDATE, DELETE, dan klausa dasar",
        questions: [
          {
            text: "Perintah SQL apa yang digunakan untuk mengambil data dari tabel?",
            optionA: "INSERT",
            optionB: "UPDATE",
            optionC: "SELECT",
            optionD: "DELETE",
            correctAnswer: "C",
            explanation: "SELECT digunakan untuk mengambil/membaca data dari satu atau lebih tabel dalam database.",
          },
          {
            text: "Klausa SQL yang digunakan untuk memfilter baris berdasarkan kondisi adalah?",
            optionA: "ORDER BY",
            optionB: "GROUP BY",
            optionC: "WHERE",
            optionD: "HAVING",
            correctAnswer: "C",
            explanation: "WHERE digunakan untuk memfilter baris data berdasarkan kondisi yang ditentukan sebelum agregasi.",
          },
          {
            text: "Apa perbedaan WHERE dan HAVING dalam SQL?",
            optionA: "WHERE untuk tabel, HAVING untuk view",
            optionB: "WHERE memfilter baris sebelum agregasi, HAVING memfilter setelah agregasi",
            optionC: "HAVING lebih cepat dari WHERE",
            optionD: "Tidak ada perbedaan keduanya sama",
            correctAnswer: "B",
            explanation: "WHERE memfilter baris individual sebelum GROUP BY, sedangkan HAVING memfilter kelompok hasil setelah GROUP BY dan fungsi agregasi.",
          },
          {
            text: "Perintah SQL untuk menambahkan baris data baru ke dalam tabel adalah?",
            optionA: "ADD",
            optionB: "CREATE",
            optionC: "INSERT INTO",
            optionD: "APPEND",
            correctAnswer: "C",
            explanation: "INSERT INTO digunakan untuk menambahkan satu atau lebih baris data baru ke dalam tabel yang sudah ada.",
          },
          {
            text: "Fungsi agregasi SQL manakah yang digunakan untuk menghitung jumlah baris?",
            optionA: "SUM()",
            optionB: "TOTAL()",
            optionC: "COUNT()",
            optionD: "NUM()",
            correctAnswer: "C",
            explanation: "COUNT() digunakan untuk menghitung jumlah baris atau nilai non-NULL dalam kolom tertentu.",
          },
        ],
      },
      {
        name: "Normalisasi & Relasi",
        description: "1NF, 2NF, 3NF, BCNF, dan relasi antar tabel",
        questions: [
          {
            text: "Apa tujuan utama dari normalisasi database?",
            optionA: "Mempercepat semua query",
            optionB: "Mengurangi redundansi data dan anomali",
            optionC: "Menambah jumlah tabel sebanyak mungkin",
            optionD: "Memperbesar kapasitas database",
            correctAnswer: "B",
            explanation: "Normalisasi bertujuan mengurangi redundansi data, mencegah anomali insert/update/delete, dan menjaga integritas data.",
          },
          {
            text: "Sebuah tabel berada dalam bentuk 1NF (First Normal Form) jika?",
            optionA: "Tidak ada primary key",
            optionB: "Semua kolom bersifat atomic (tidak ada nilai berulang dalam satu sel)",
            optionC: "Semua atribut bergantung pada primary key",
            optionD: "Tidak ada foreign key",
            correctAnswer: "B",
            explanation: "1NF mensyaratkan setiap kolom harus bersifat atomic (satu nilai per sel) dan tidak boleh ada repeating groups.",
          },
          {
            text: "Relasi Many-to-Many antara dua tabel biasanya diimplementasikan dengan?",
            optionA: "Menambah kolom di salah satu tabel",
            optionB: "Membuat tabel junction/bridge di antara keduanya",
            optionC: "Menggabungkan kedua tabel menjadi satu",
            optionD: "Menggunakan VIEW",
            correctAnswer: "B",
            explanation: "Relasi Many-to-Many memerlukan tabel junction (bridge table) yang menyimpan foreign key dari kedua tabel untuk merepresentasikan hubungan tersebut.",
          },
          {
            text: "Primary key pada sebuah tabel digunakan untuk?",
            optionA: "Mengurutkan data secara otomatis",
            optionB: "Mengidentifikasi setiap baris secara unik",
            optionC: "Menyimpan data dalam bentuk enkripsi",
            optionD: "Menghubungkan tabel dengan database lain",
            correctAnswer: "B",
            explanation: "Primary key memastikan setiap baris dalam tabel memiliki identitas unik yang tidak boleh NULL atau duplikat.",
          },
          {
            text: "Apa yang dimaksud dengan Foreign Key?",
            optionA: "Key dari database asing/luar negeri",
            optionB: "Kolom yang nilainya mereferensikan primary key tabel lain",
            optionC: "Primary key yang dienkripsi",
            optionD: "Key yang digunakan untuk sorting",
            correctAnswer: "B",
            explanation: "Foreign key adalah kolom (atau kombinasi kolom) yang nilainya merujuk ke primary key tabel lain, digunakan untuk membuat relasi antar tabel.",
          },
        ],
      },
      {
        name: "JOIN & Transaksi",
        description: "INNER JOIN, LEFT JOIN, transaksi ACID, dan indexing",
        questions: [
          {
            text: "INNER JOIN mengembalikan?",
            optionA: "Semua baris dari tabel kiri",
            optionB: "Semua baris dari tabel kanan",
            optionC: "Hanya baris yang memiliki kecocokan di kedua tabel",
            optionD: "Semua baris dari kedua tabel",
            correctAnswer: "C",
            explanation: "INNER JOIN hanya mengembalikan baris yang memiliki kecocokan (matching) di kedua tabel berdasarkan kondisi join yang ditentukan.",
          },
          {
            text: "Apa kepanjangan dari ACID dalam konteks transaksi database?",
            optionA: "Atomicity, Consistency, Isolation, Durability",
            optionB: "Access, Control, Integration, Data",
            optionC: "Atomic, Concurrent, Integrated, Distributed",
            optionD: "Availability, Consistency, Independence, Durability",
            correctAnswer: "A",
            explanation: "ACID adalah singkatan dari Atomicity (semua atau tidak sama sekali), Consistency (data selalu valid), Isolation (transaksi independen), dan Durability (data tersimpan permanen).",
          },
          {
            text: "Perintah ROLLBACK dalam transaksi SQL digunakan untuk?",
            optionA: "Menyimpan perubahan secara permanen",
            optionB: "Membatalkan semua perubahan dalam transaksi yang sedang berjalan",
            optionC: "Memulai transaksi baru",
            optionD: "Mengunci tabel selama transaksi",
            correctAnswer: "B",
            explanation: "ROLLBACK membatalkan semua perubahan yang telah dilakukan sejak BEGIN TRANSACTION, mengembalikan database ke kondisi sebelum transaksi dimulai.",
          },
          {
            text: "Index pada database digunakan untuk?",
            optionA: "Menyimpan data secara terenkripsi",
            optionB: "Mempercepat operasi pencarian/query",
            optionC: "Membuat relasi antar tabel",
            optionD: "Memvalidasi tipe data kolom",
            correctAnswer: "B",
            explanation: "Index membuat struktur data tambahan yang memungkinkan database menemukan baris secara cepat tanpa harus melakukan full table scan.",
          },
          {
            text: "LEFT JOIN menghasilkan?",
            optionA: "Hanya baris yang cocok di kedua tabel",
            optionB: "Semua baris tabel kiri, dan baris yang cocok dari tabel kanan (NULL jika tidak ada)",
            optionC: "Semua baris dari kedua tabel tanpa kecocokan",
            optionD: "Baris yang tidak cocok di kedua tabel",
            correctAnswer: "B",
            explanation: "LEFT JOIN mengembalikan semua baris dari tabel kiri, dan untuk baris yang tidak memiliki kecocokan di tabel kanan, kolom tabel kanan akan berisi NULL.",
          },
        ],
      },
    ],
  },
  {
    name: "Jaringan Komputer",
    description: "Model OSI, TCP/IP, Protokol, IP Address, Keamanan",
    quizzes: [
      {
        name: "Model OSI & TCP/IP",
        description: "7 layer OSI dan 4 layer TCP/IP",
        questions: [
          {
            text: "Berapa jumlah layer pada model OSI?",
            optionA: "4",
            optionB: "5",
            optionC: "6",
            optionD: "7",
            correctAnswer: "D",
            explanation: "Model OSI terdiri dari 7 layer: Physical, Data Link, Network, Transport, Session, Presentation, dan Application.",
          },
          {
            text: "Layer mana pada model OSI yang bertanggung jawab untuk routing paket data?",
            optionA: "Data Link Layer",
            optionB: "Network Layer",
            optionC: "Transport Layer",
            optionD: "Session Layer",
            correctAnswer: "B",
            explanation: "Network Layer (Layer 3) bertanggung jawab untuk routing, yaitu menentukan jalur terbaik untuk pengiriman paket data antar jaringan.",
          },
          {
            text: "Protokol HTTP berada pada layer apa dalam model OSI?",
            optionA: "Transport Layer",
            optionB: "Session Layer",
            optionC: "Presentation Layer",
            optionD: "Application Layer",
            correctAnswer: "D",
            explanation: "HTTP adalah protokol pada Application Layer (Layer 7) yang digunakan untuk komunikasi web antara client dan server.",
          },
          {
            text: "Model TCP/IP memiliki berapa layer?",
            optionA: "3",
            optionB: "4",
            optionC: "5",
            optionD: "7",
            correctAnswer: "B",
            explanation: "Model TCP/IP terdiri dari 4 layer: Network Access, Internet, Transport, dan Application.",
          },
          {
            text: "Layer Transport pada model TCP/IP bertanggung jawab untuk?",
            optionA: "Routing paket antar jaringan",
            optionB: "Komunikasi end-to-end yang andal antara aplikasi",
            optionC: "Konversi data ke format yang dapat ditransmisikan",
            optionD: "Mengontrol akses ke media fisik",
            correctAnswer: "B",
            explanation: "Layer Transport menyediakan komunikasi end-to-end, termasuk pengendalian aliran, deteksi error, dan pengurutan data (contoh: TCP dan UDP).",
          },
        ],
      },
      {
        name: "IP Address & Protokol",
        description: "IPv4, IPv6, subnetting, TCP, UDP, DNS, DHCP",
        questions: [
          {
            text: "Berapa bit panjang alamat IPv4?",
            optionA: "16 bit",
            optionB: "32 bit",
            optionC: "64 bit",
            optionD: "128 bit",
            correctAnswer: "B",
            explanation: "IPv4 menggunakan 32 bit, yang dibagi menjadi 4 oktet masing-masing 8 bit, menghasilkan format seperti 192.168.1.1.",
          },
          {
            text: "Apa perbedaan utama antara TCP dan UDP?",
            optionA: "TCP lebih cepat dari UDP",
            optionB: "TCP connection-oriented dan reliable, UDP connectionless dan tidak menjamin delivery",
            optionC: "UDP hanya untuk jaringan lokal",
            optionD: "TCP tidak mendukung enkripsi",
            correctAnswer: "B",
            explanation: "TCP menjamin pengiriman data dengan mekanisme acknowledgment dan retransmission (reliable), sedangkan UDP lebih cepat tapi tidak menjamin delivery (unreliable).",
          },
          {
            text: "Fungsi utama DNS (Domain Name System) adalah?",
            optionA: "Mengalokasikan IP address secara dinamis",
            optionB: "Menerjemahkan nama domain menjadi IP address",
            optionC: "Mengenkripsi komunikasi jaringan",
            optionD: "Mengelola routing antar jaringan",
            correctAnswer: "B",
            explanation: "DNS berfungsi sebagai 'buku telepon' internet yang menerjemahkan nama domain yang mudah diingat (seperti google.com) menjadi alamat IP yang digunakan komputer.",
          },
          {
            text: "DHCP digunakan untuk?",
            optionA: "Mengenkripsi paket data",
            optionB: "Mengirim email secara otomatis",
            optionC: "Memberikan IP address secara otomatis kepada perangkat di jaringan",
            optionD: "Memfilter lalu lintas jaringan",
            correctAnswer: "C",
            explanation: "DHCP (Dynamic Host Configuration Protocol) secara otomatis mengalokasikan IP address, subnet mask, gateway, dan informasi jaringan lainnya kepada perangkat.",
          },
          {
            text: "Port berapa yang digunakan protokol HTTPS?",
            optionA: "80",
            optionB: "21",
            optionC: "443",
            optionD: "22",
            correctAnswer: "C",
            explanation: "HTTPS (HTTP Secure) menggunakan port 443 secara default, sedangkan HTTP menggunakan port 80.",
          },
        ],
      },
    ],
  },
  {
    name: "Sistem Operasi",
    description: "Proses, Thread, Memori, Deadlock, Sistem File",
    quizzes: [
      {
        name: "Proses & Thread",
        description: "Manajemen proses, thread, dan penjadwalan CPU",
        questions: [
          {
            text: "Apa perbedaan utama antara proses dan thread?",
            optionA: "Thread memiliki memory space sendiri, proses berbagi",
            optionB: "Proses memiliki memory space sendiri, thread berbagi memory dalam proses yang sama",
            optionC: "Proses lebih ringan dari thread",
            optionD: "Thread tidak bisa berjalan secara paralel",
            correctAnswer: "B",
            explanation: "Setiap proses memiliki memory space yang terpisah dan independen, sedangkan thread-thread dalam satu proses berbagi memory space yang sama.",
          },
          {
            text: "Algoritma penjadwalan CPU yang memberikan prioritas pada proses dengan burst time terpendek adalah?",
            optionA: "FCFS (First Come First Served)",
            optionB: "Round Robin",
            optionC: "SJF (Shortest Job First)",
            optionD: "Priority Scheduling",
            correctAnswer: "C",
            explanation: "SJF memilih proses dengan CPU burst time terpendek berikutnya untuk dieksekusi, menghasilkan rata-rata waiting time minimum.",
          },
          {
            text: "Context switching adalah?",
            optionA: "Pergantian mode pengguna",
            optionB: "Proses menyimpan state proses saat ini dan memuat state proses berikutnya",
            optionC: "Pengalihan memori virtual",
            optionD: "Perpindahan data antar hard disk",
            correctAnswer: "B",
            explanation: "Context switching terjadi ketika OS menyimpan state (context) proses yang sedang berjalan dan memuat context proses lain yang akan dieksekusi.",
          },
          {
            text: "Kondisi race condition dalam pemrograman konkuren terjadi ketika?",
            optionA: "Dua proses berjalan dalam kecepatan yang berbeda",
            optionB: "Hasil program bergantung pada urutan atau timing eksekusi yang tidak dapat diprediksi",
            optionC: "Sistem mengalami kelebihan beban",
            optionD: "Thread berjalan lebih cepat dari proses",
            correctAnswer: "B",
            explanation: "Race condition terjadi ketika dua atau lebih thread mengakses dan memodifikasi resource bersama secara bersamaan, menghasilkan output yang tidak deterministik.",
          },
          {
            text: "Mutex digunakan dalam pemrograman konkuren untuk?",
            optionA: "Meningkatkan kecepatan eksekusi thread",
            optionB: "Memastikan hanya satu thread yang mengakses critical section pada satu waktu",
            optionC: "Mendistribusikan beban kerja antar thread",
            optionD: "Menghentikan thread yang tidak responsif",
            correctAnswer: "B",
            explanation: "Mutex (Mutual Exclusion) adalah mekanisme sinkronisasi yang memastikan hanya satu thread yang dapat mengeksekusi critical section (bagian kode yang mengakses shared resource) pada satu waktu.",
          },
        ],
      },
      {
        name: "Memori & Deadlock",
        description: "Virtual memory, paging, segmentasi, dan deadlock",
        questions: [
          {
            text: "Virtual memory memungkinkan?",
            optionA: "Proses menggunakan lebih banyak memori dari RAM yang tersedia secara fisik",
            optionB: "Memori menjadi lebih cepat dari RAM biasa",
            optionC: "Beberapa proses menggunakan memori yang sama",
            optionD: "Proses berjalan tanpa memerlukan RAM",
            correctAnswer: "A",
            explanation: "Virtual memory menggunakan disk sebagai ekstensi RAM, memungkinkan proses menggunakan memori melebihi kapasitas fisik RAM yang tersedia.",
          },
          {
            text: "Deadlock terjadi ketika?",
            optionA: "Sistem kehabisan memori",
            optionB: "Sekelompok proses saling menunggu resource yang dipegang proses lain dalam kelompok tersebut",
            optionC: "CPU mengalami overload",
            optionD: "Thread berjalan terlalu lambat",
            correctAnswer: "B",
            explanation: "Deadlock adalah situasi di mana dua atau lebih proses saling menunggu resource yang dimiliki proses lain, sehingga tidak ada yang bisa melanjutkan eksekusi.",
          },
          {
            text: "Manakah yang BUKAN merupakan kondisi perlu terjadinya deadlock (Coffman conditions)?",
            optionA: "Mutual Exclusion",
            optionB: "Hold and Wait",
            optionC: "Preemption",
            optionD: "Circular Wait",
            correctAnswer: "C",
            explanation: "Empat kondisi Coffman untuk deadlock adalah: Mutual Exclusion, Hold and Wait, No Preemption, dan Circular Wait. Preemption (kemampuan mengambil resource paksa) justru MENCEGAH deadlock, bukan menyebabkannya.",
          },
          {
            text: "Teknik paging dalam manajemen memori membagi memori menjadi?",
            optionA: "Segmen-segmen dengan ukuran variabel",
            optionB: "Halaman-halaman (pages) dengan ukuran tetap",
            optionC: "Partisi-partisi yang tidak merata",
            optionD: "Blok-blok yang dapat diubah ukurannya",
            correctAnswer: "B",
            explanation: "Paging membagi memori fisik dan virtual menjadi unit-unit dengan ukuran tetap yang disebut page (untuk memori virtual) dan frame (untuk memori fisik).",
          },
          {
            text: "Thrashing dalam konteks sistem operasi terjadi ketika?",
            optionA: "CPU bekerja 100% tanpa melakukan paging",
            optionB: "Sistem menghabiskan lebih banyak waktu untuk paging daripada eksekusi proses",
            optionC: "Hard disk penuh dan tidak ada ruang untuk swap",
            optionD: "Program menggunakan terlalu banyak CPU time",
            correctAnswer: "B",
            explanation: "Thrashing terjadi ketika sistem terus-menerus melakukan page fault dan page replacement, menghabiskan sebagian besar waktu untuk operasi I/O disk daripada eksekusi instruksi program.",
          },
        ],
      },
    ],
  },
  {
    name: "Pemrograman Web",
    description: "HTML, CSS, JavaScript, Backend, REST API, Keamanan Web",
    quizzes: [
      {
        name: "HTML & CSS",
        description: "Struktur halaman web, styling, dan layout",
        questions: [
          {
            text: "Tag HTML yang digunakan untuk membuat tautan (hyperlink) adalah?",
            optionA: "<link>",
            optionB: "<href>",
            optionC: "<a>",
            optionD: "<url>",
            correctAnswer: "C",
            explanation: "Tag <a> (anchor) digunakan untuk membuat hyperlink, dengan atribut href menentukan tujuan URL.",
          },
          {
            text: "Properti CSS yang digunakan untuk mengatur jarak di luar border elemen adalah?",
            optionA: "padding",
            optionB: "border-spacing",
            optionC: "margin",
            optionD: "spacing",
            correctAnswer: "C",
            explanation: "margin mengatur jarak di luar border elemen, sedangkan padding mengatur jarak di dalam border (antara konten dan border).",
          },
          {
            text: "Apa kepanjangan dari CSS?",
            optionA: "Computer Style Sheets",
            optionB: "Cascading Style Sheets",
            optionC: "Creative Style Sheets",
            optionD: "Colorful Style Sheets",
            correctAnswer: "B",
            explanation: "CSS adalah singkatan dari Cascading Style Sheets, bahasa yang digunakan untuk mendeskripsikan presentasi/tampilan dokumen HTML.",
          },
          {
            text: "Display property CSS mana yang mengatur elemen sebagai blok fleksibel?",
            optionA: "display: block",
            optionB: "display: inline",
            optionC: "display: flex",
            optionD: "display: grid",
            correctAnswer: "C",
            explanation: "display: flex mengaktifkan Flexbox layout, memudahkan pengaturan tata letak elemen secara satu dimensi (baris atau kolom).",
          },
          {
            text: "Atribut HTML yang digunakan untuk menentukan gaya inline pada elemen adalah?",
            optionA: "class",
            optionB: "style",
            optionC: "css",
            optionD: "design",
            correctAnswer: "B",
            explanation: "Atribut style digunakan untuk menerapkan CSS secara langsung (inline) pada elemen HTML tertentu, contoh: <p style='color: red;'>.",
          },
        ],
      },
      {
        name: "JavaScript & REST API",
        description: "DOM, event, fetch API, dan arsitektur REST",
        questions: [
          {
            text: "Apa yang dimaksud dengan DOM dalam konteks web?",
            optionA: "Database Object Management",
            optionB: "Document Object Model — representasi terstruktur dari dokumen HTML",
            optionC: "Dynamic Object Method",
            optionD: "Data Operation Module",
            correctAnswer: "B",
            explanation: "DOM (Document Object Model) adalah antarmuka pemrograman yang merepresentasikan dokumen HTML sebagai pohon objek yang dapat dimanipulasi dengan JavaScript.",
          },
          {
            text: "Metode HTTP apa yang digunakan untuk membuat resource baru dalam REST API?",
            optionA: "GET",
            optionB: "PUT",
            optionC: "POST",
            optionD: "PATCH",
            correctAnswer: "C",
            explanation: "POST digunakan untuk membuat resource baru. GET untuk membaca, PUT untuk mengganti seluruh resource, PATCH untuk memperbarui sebagian, DELETE untuk menghapus.",
          },
          {
            text: "JSON (JavaScript Object Notation) digunakan untuk?",
            optionA: "Menjalankan kode JavaScript di server",
            optionB: "Format pertukaran data yang ringan dan mudah dibaca",
            optionC: "Membuat animasi pada web",
            optionD: "Menyimpan data di browser",
            correctAnswer: "B",
            explanation: "JSON adalah format teks ringan untuk pertukaran data yang mudah dibaca manusia dan mudah diparse oleh mesin, banyak digunakan dalam REST API.",
          },
          {
            text: "Status code HTTP 404 berarti?",
            optionA: "Request berhasil",
            optionB: "Server error internal",
            optionC: "Resource tidak ditemukan",
            optionD: "Unauthorized access",
            correctAnswer: "C",
            explanation: "Status code 404 Not Found menandakan bahwa server tidak dapat menemukan resource yang diminta. 200 untuk sukses, 500 untuk server error, 401 untuk unauthorized.",
          },
          {
            text: "Apa yang dimaksud dengan CORS (Cross-Origin Resource Sharing)?",
            optionA: "Protokol enkripsi untuk HTTPS",
            optionB: "Mekanisme keamanan browser yang mengatur akses resource dari domain berbeda",
            optionC: "Format data untuk REST API",
            optionD: "Metode autentikasi pengguna",
            correctAnswer: "B",
            explanation: "CORS adalah mekanisme keamanan berbasis HTTP header yang memungkinkan atau membatasi web applications di satu origin untuk mengakses resource dari origin yang berbeda.",
          },
        ],
      },
    ],
  },
  {
    name: "Pemrograman Berorientasi Objek",
    description: "Konsep OOP, Inheritance, Polymorphism, Design Pattern",
    quizzes: [
      {
        name: "Konsep Dasar OOP",
        description: "Class, object, encapsulation, abstraction",
        questions: [
          {
            text: "Manakah yang BUKAN merupakan pilar utama OOP?",
            optionA: "Encapsulation",
            optionB: "Inheritance",
            optionC: "Compilation",
            optionD: "Polymorphism",
            correctAnswer: "C",
            explanation: "Empat pilar OOP adalah Encapsulation, Inheritance, Polymorphism, dan Abstraction. Compilation adalah proses konversi kode sumber ke kode mesin, bukan konsep OOP.",
          },
          {
            text: "Encapsulation dalam OOP bertujuan untuk?",
            optionA: "Membuat kelas yang dapat diwariskan",
            optionB: "Menyembunyikan detail implementasi dan melindungi data internal",
            optionC: "Memungkinkan satu method memiliki banyak implementasi",
            optionD: "Membuat object dari kelas abstrak",
            correctAnswer: "B",
            explanation: "Encapsulation menyembunyikan detail internal implementasi dan data dari akses luar, hanya mengekspos interface yang diperlukan melalui method public.",
          },
          {
            text: "Apa perbedaan antara Class dan Object?",
            optionA: "Object adalah blueprint, Class adalah instansinya",
            optionB: "Class adalah blueprint/template, Object adalah instansi dari Class",
            optionC: "Class dan Object adalah hal yang sama",
            optionD: "Object hanya ada dalam bahasa Java",
            correctAnswer: "B",
            explanation: "Class adalah blueprint atau template yang mendefinisikan atribut dan perilaku, sedangkan Object adalah instansi konkret yang dibuat dari Class tersebut.",
          },
          {
            text: "Constructor dalam OOP digunakan untuk?",
            optionA: "Menghapus object dari memori",
            optionB: "Menginisialisasi object saat dibuat",
            optionC: "Mewarisi sifat dari kelas induk",
            optionD: "Mendefinisikan method abstrak",
            correctAnswer: "B",
            explanation: "Constructor adalah method khusus yang dipanggil secara otomatis saat object dibuat, digunakan untuk menginisialisasi atribut object ke nilai awal.",
          },
          {
            text: "Access modifier 'private' pada atribut berarti?",
            optionA: "Dapat diakses dari mana saja",
            optionB: "Hanya dapat diakses dalam kelas yang sama",
            optionC: "Dapat diakses oleh subclass",
            optionD: "Dapat diakses dalam satu package",
            correctAnswer: "B",
            explanation: "Access modifier private membatasi akses atribut atau method hanya dari dalam kelas itu sendiri, mendukung prinsip encapsulation.",
          },
        ],
      },
      {
        name: "Inheritance & Polymorphism",
        description: "Pewarisan, overriding, overloading, dan interface",
        questions: [
          {
            text: "Method overriding terjadi ketika?",
            optionA: "Subclass mendefinisikan ulang method yang sudah ada di superclass dengan signature yang sama",
            optionB: "Dua method dalam kelas yang sama memiliki nama yang sama tapi parameter berbeda",
            optionC: "Sebuah method memanggil dirinya sendiri",
            optionD: "Method tidak dapat diakses dari luar kelas",
            correctAnswer: "A",
            explanation: "Method overriding terjadi ketika subclass menyediakan implementasi spesifik untuk method yang sudah didefinisikan di superclass dengan nama dan signature yang sama.",
          },
          {
            text: "Method overloading adalah?",
            optionA: "Subclass mendefinisikan ulang method superclass",
            optionB: "Beberapa method dalam kelas yang sama memiliki nama sama tapi parameter berbeda",
            optionC: "Method yang dipanggil terlalu sering",
            optionD: "Method yang diwarisi dari superclass",
            correctAnswer: "B",
            explanation: "Method overloading memungkinkan beberapa method dengan nama yang sama dalam satu kelas, asalkan signature-nya berbeda (jumlah atau tipe parameter).",
          },
          {
            text: "Apa yang dimaksud dengan Interface dalam OOP?",
            optionA: "Antarmuka grafis pengguna",
            optionB: "Kontrak yang mendefinisikan method yang harus diimplementasikan oleh class",
            optionC: "Kelas yang tidak bisa diinstansiasi",
            optionD: "Method yang menghubungkan dua kelas",
            correctAnswer: "B",
            explanation: "Interface mendefinisikan kontrak berupa sekumpulan method abstrak yang harus diimplementasikan oleh class yang menggunakannya (implements).",
          },
          {
            text: "Keyword 'super' dalam OOP digunakan untuk?",
            optionA: "Membuat kelas menjadi superclass",
            optionB: "Memanggil constructor atau method dari kelas induk (superclass)",
            optionC: "Mendefinisikan method abstract",
            optionD: "Mengakses method private",
            correctAnswer: "B",
            explanation: "Keyword super digunakan untuk memanggil constructor superclass (super()) atau method superclass yang di-override (super.methodName()) dari subclass.",
          },
          {
            text: "Abstraction dalam OOP berarti?",
            optionA: "Menyembunyikan data dengan access modifier",
            optionB: "Menyembunyikan detail kompleksitas dan hanya menampilkan fitur yang relevan",
            optionC: "Mewariskan sifat dari kelas induk",
            optionD: "Membuat multiple implementasi dari satu method",
            correctAnswer: "B",
            explanation: "Abstraction menyembunyikan detail implementasi yang kompleks dan hanya mengekspos interface yang relevan kepada pengguna, mengurangi kompleksitas dari perspektif user.",
          },
        ],
      },
    ],
  },
  {
    name: "Matematika Diskrit",
    description: "Logika, Himpunan, Graf, Kombinatorik, Relasi",
    quizzes: [
      {
        name: "Logika & Himpunan",
        description: "Proposisi, tabel kebenaran, operasi himpunan",
        questions: [
          {
            text: "Dalam logika proporsional, operator AND (∧) menghasilkan TRUE hanya ketika?",
            optionA: "Salah satu operand bernilai TRUE",
            optionB: "Kedua operand bernilai TRUE",
            optionC: "Kedua operand bernilai FALSE",
            optionD: "Salah satu operand bernilai FALSE",
            correctAnswer: "B",
            explanation: "Operator AND menghasilkan TRUE hanya jika kedua operand bernilai TRUE. Jika salah satu atau keduanya FALSE, hasilnya FALSE.",
          },
          {
            text: "Negasi (NOT) dari proposisi 'Hari ini hujan' adalah?",
            optionA: "Hari ini cerah",
            optionB: "Hari ini tidak hujan",
            optionC: "Hari ini mungkin hujan",
            optionD: "Hari ini sangat hujan",
            correctAnswer: "B",
            explanation: "Negasi (NOT) membalik nilai kebenaran proposisi. Negasi dari 'Hari ini hujan' adalah 'Hari ini tidak hujan'.",
          },
          {
            text: "Operasi union (∪) pada himpunan menghasilkan?",
            optionA: "Elemen yang ada di kedua himpunan",
            optionB: "Elemen yang ada di A tapi tidak di B",
            optionC: "Semua elemen yang ada di A atau B atau keduanya",
            optionD: "Elemen yang tidak ada di kedua himpunan",
            correctAnswer: "C",
            explanation: "Union (A ∪ B) menghasilkan himpunan yang berisi semua elemen yang ada di A, di B, atau di keduanya.",
          },
          {
            text: "Operasi intersection (∩) pada himpunan A = {1,2,3,4} dan B = {3,4,5,6} menghasilkan?",
            optionA: "{1,2,3,4,5,6}",
            optionB: "{1,2}",
            optionC: "{3,4}",
            optionD: "{5,6}",
            correctAnswer: "C",
            explanation: "Intersection (A ∩ B) menghasilkan elemen yang ada di KEDUA himpunan. Elemen yang ada di A dan B sekaligus adalah {3,4}.",
          },
          {
            text: "Sebuah proposisi tautologi adalah?",
            optionA: "Proposisi yang selalu bernilai FALSE",
            optionB: "Proposisi yang nilainya bergantung pada kondisi",
            optionC: "Proposisi yang selalu bernilai TRUE",
            optionD: "Proposisi yang tidak dapat ditentukan nilainya",
            correctAnswer: "C",
            explanation: "Tautologi adalah proposisi yang selalu bernilai TRUE terlepas dari nilai kebenaran variabel proposisionalnya.",
          },
        ],
      },
      {
        name: "Graf & Kombinatorik",
        description: "Teori graf, pohon rentang, permutasi, kombinasi",
        questions: [
          {
            text: "Apa yang dimaksud dengan graf berbobot (weighted graph)?",
            optionA: "Graf dengan banyak node",
            optionB: "Graf di mana setiap edge memiliki nilai/bobot numerik",
            optionC: "Graf tanpa siklus",
            optionD: "Graf dengan semua node terhubung",
            correctAnswer: "B",
            explanation: "Graf berbobot adalah graf di mana setiap edge (sisi) memiliki nilai numerik yang disebut bobot, biasanya merepresentasikan jarak, biaya, atau kapasitas.",
          },
          {
            text: "Berapa banyak cara memilih 3 orang dari 5 orang (tanpa memperhatikan urutan)?",
            optionA: "10",
            optionB: "15",
            optionC: "20",
            optionD: "60",
            correctAnswer: "A",
            explanation: "Ini adalah kombinasi C(5,3) = 5!/(3!×2!) = (5×4)/(2×1) = 10. Kombinasi digunakan karena urutan tidak diperhatikan.",
          },
          {
            text: "Perbedaan permutasi dan kombinasi adalah?",
            optionA: "Permutasi untuk bilangan, kombinasi untuk huruf",
            optionB: "Permutasi memperhatikan urutan, kombinasi tidak",
            optionC: "Kombinasi selalu lebih besar dari permutasi",
            optionD: "Tidak ada perbedaan",
            correctAnswer: "B",
            explanation: "Permutasi P(n,r) memperhatikan urutan pemilihan, sedangkan Kombinasi C(n,r) tidak memperhatikan urutan. P(n,r) = n!/(n-r)!, C(n,r) = n!/(r!×(n-r)!).",
          },
          {
            text: "Graf yang tidak memiliki siklus (cycle) disebut?",
            optionA: "Graf lengkap",
            optionB: "Graf berbobot",
            optionC: "Graf berarah",
            optionD: "Graf asiklik (acyclic graph) / pohon",
            correctAnswer: "D",
            explanation: "Graf asiklik adalah graf yang tidak memiliki siklus (cycle). Jika juga terhubung, disebut pohon (tree).",
          },
          {
            text: "Algoritma Dijkstra digunakan untuk?",
            optionA: "Mencari siklus dalam graf",
            optionB: "Mencari jalur terpendek dari satu node ke semua node lain dalam graf berbobot",
            optionC: "Mengurutkan elemen graf",
            optionD: "Mewarnai graf dengan warna minimum",
            correctAnswer: "B",
            explanation: "Algoritma Dijkstra mencari jalur terpendek dari satu node sumber ke semua node lain dalam graf berbobot tidak negatif.",
          },
        ],
      },
    ],
  },
  {
    name: "Kecerdasan Buatan",
    description: "Konsep AI, Machine Learning, Neural Network, NLP",
    quizzes: [
      {
        name: "Konsep AI & Machine Learning",
        description: "Supervised, unsupervised learning, dan algoritma ML dasar",
        questions: [
          {
            text: "Apa perbedaan Supervised Learning dan Unsupervised Learning?",
            optionA: "Supervised menggunakan GPU, Unsupervised menggunakan CPU",
            optionB: "Supervised belajar dari data berlabel, Unsupervised menemukan pola dari data tanpa label",
            optionC: "Unsupervised lebih akurat dari Supervised",
            optionD: "Supervised hanya untuk klasifikasi, Unsupervised hanya untuk regresi",
            correctAnswer: "B",
            explanation: "Supervised learning menggunakan data training yang sudah berlabel (ada jawaban benar), sedangkan Unsupervised learning menemukan pola atau struktur tersembunyi dari data tanpa label.",
          },
          {
            text: "Algoritma K-Nearest Neighbors (KNN) melakukan klasifikasi berdasarkan?",
            optionA: "Model matematika yang dilatih terlebih dahulu",
            optionB: "K data terdekat dari data yang akan diklasifikasikan",
            optionC: "Probabilitas Bayesian",
            optionD: "Pohon keputusan yang dibuat secara acak",
            correctAnswer: "B",
            explanation: "KNN mengklasifikasikan data baru berdasarkan mayoritas kelas dari K tetangga terdekatnya menggunakan metrik jarak seperti Euclidean distance.",
          },
          {
            text: "Overfitting dalam machine learning terjadi ketika?",
            optionA: "Model terlalu sederhana untuk menangkap pola data",
            optionB: "Model terlalu kompleks sehingga menghafal data training tapi gagal generalisasi ke data baru",
            optionC: "Data training terlalu sedikit",
            optionD: "Algoritma tidak konvergen",
            correctAnswer: "B",
            explanation: "Overfitting terjadi ketika model 'menghafal' data training termasuk noise-nya, menghasilkan performa sangat baik pada training data tapi buruk pada data baru (test data).",
          },
          {
            text: "Apa fungsi Confusion Matrix dalam evaluasi model ML?",
            optionA: "Menampilkan bobot dari neural network",
            optionB: "Menunjukkan perbandingan prediksi model dengan nilai aktual (TP, TN, FP, FN)",
            optionC: "Mengoptimalkan hyperparameter model",
            optionD: "Memvisualisasikan distribusi data training",
            correctAnswer: "B",
            explanation: "Confusion Matrix menampilkan True Positive, True Negative, False Positive, dan False Negative, membantu mengevaluasi performa model klasifikasi secara detail.",
          },
          {
            text: "Clustering dalam Unsupervised Learning bertujuan untuk?",
            optionA: "Memprediksi nilai numerik",
            optionB: "Mengkelompokkan data yang mirip ke dalam cluster yang sama",
            optionC: "Mengklasifikasikan data ke kelas yang sudah ditentukan",
            optionD: "Mengurangi dimensi data",
            correctAnswer: "B",
            explanation: "Clustering adalah teknik unsupervised learning yang mengelompokkan data berdasarkan kemiripan, sehingga data dalam satu cluster lebih mirip satu sama lain daripada dengan data di cluster lain.",
          },
        ],
      },
      {
        name: "Neural Network & Deep Learning",
        description: "Perceptron, backpropagation, CNN, RNN",
        questions: [
          {
            text: "Apa fungsi activation function dalam neural network?",
            optionA: "Menginisialisasi bobot jaringan",
            optionB: "Memperkenalkan non-linearitas sehingga jaringan dapat mempelajari pola kompleks",
            optionC: "Menghitung loss function",
            optionD: "Mengatur learning rate",
            correctAnswer: "B",
            explanation: "Activation function memperkenalkan non-linearitas ke dalam neural network, memungkinkannya mempelajari dan merepresentasikan hubungan yang kompleks dalam data.",
          },
          {
            text: "Backpropagation dalam neural network digunakan untuk?",
            optionA: "Memproses data dari output ke input",
            optionB: "Menghitung dan menyebarkan gradient error untuk memperbarui bobot jaringan",
            optionC: "Menginisialisasi bobot awal jaringan",
            optionD: "Menambah layer baru ke jaringan",
            correctAnswer: "B",
            explanation: "Backpropagation menghitung gradient loss terhadap setiap bobot menggunakan chain rule, kemudian menyebarkan error dari output ke input untuk memperbarui bobot agar loss berkurang.",
          },
          {
            text: "CNN (Convolutional Neural Network) paling cocok digunakan untuk?",
            optionA: "Analisis data sekuensial seperti teks",
            optionB: "Pemrosesan data gambar dan video",
            optionC: "Prediksi deret waktu",
            optionD: "Clustering data tabular",
            correctAnswer: "B",
            explanation: "CNN dirancang khusus untuk memproses data grid seperti gambar, menggunakan operasi konvolusi untuk mengekstrak fitur spasial secara hirarki.",
          },
          {
            text: "Apa yang dimaksud dengan transfer learning?",
            optionA: "Memindahkan model dari satu komputer ke komputer lain",
            optionB: "Menggunakan model yang sudah dilatih pada satu task sebagai starting point untuk task lain",
            optionC: "Mentransfer data antar dataset",
            optionD: "Melatih model dengan data dari domain yang berbeda secara bersamaan",
            correctAnswer: "B",
            explanation: "Transfer learning memanfaatkan pengetahuan yang sudah dipelajari model dari satu task (biasanya dengan dataset besar) sebagai fondasi untuk task lain, mengurangi kebutuhan data dan waktu training.",
          },
          {
            text: "Dropout dalam deep learning digunakan untuk?",
            optionA: "Mempercepat training dengan mengurangi jumlah komputasi",
            optionB: "Mencegah overfitting dengan secara acak menonaktifkan sebagian neuron selama training",
            optionC: "Menghapus layer yang tidak diperlukan",
            optionD: "Mengatur learning rate secara dinamis",
            correctAnswer: "B",
            explanation: "Dropout adalah teknik regularisasi yang secara acak menonaktifkan sebagian neuron selama training, memaksa jaringan untuk tidak bergantung terlalu pada neuron tertentu dan mengurangi overfitting.",
          },
        ],
      },
    ],
  },
  {
    name: "Rekayasa Perangkat Lunak",
    description: "SDLC, Metodologi, Testing, Desain Sistem, UML",
    quizzes: [
      {
        name: "SDLC & Metodologi",
        description: "Waterfall, Agile, Scrum, dan fase pengembangan",
        questions: [
          {
            text: "SDLC singkatan dari?",
            optionA: "Software Design and Lifecycle",
            optionB: "System Development Life Cycle",
            optionC: "Software Development Life Cycle",
            optionD: "Structured Development Language Cycle",
            correctAnswer: "C",
            explanation: "SDLC adalah Software Development Life Cycle, kerangka kerja yang mendefinisikan proses dan tahapan pengembangan perangkat lunak dari awal hingga pemeliharaan.",
          },
          {
            text: "Perbedaan utama metodologi Waterfall dan Agile adalah?",
            optionA: "Waterfall lebih mahal dari Agile",
            optionB: "Waterfall sekuensial dan kaku, Agile iteratif dan fleksibel terhadap perubahan",
            optionC: "Agile tidak memerlukan dokumentasi",
            optionD: "Waterfall selalu menghasilkan software yang lebih baik",
            correctAnswer: "B",
            explanation: "Waterfall mengikuti tahapan sekuensial yang kaku, sedangkan Agile menggunakan pendekatan iteratif-inkremental yang lebih adaptif terhadap perubahan requirement.",
          },
          {
            text: "Dalam Scrum, Sprint adalah?",
            optionA: "Anggota tim yang berlari cepat",
            optionB: "Iterasi pendek (biasanya 1-4 minggu) untuk menghasilkan increment produk yang bisa digunakan",
            optionC: "Dokumen requirement yang lengkap",
            optionD: "Rapat harian tim pengembang",
            correctAnswer: "B",
            explanation: "Sprint dalam Scrum adalah iterasi pendek dengan durasi tetap (1-4 minggu) di mana tim mengembangkan dan menghasilkan increment produk yang berpotensi dapat dirilis.",
          },
          {
            text: "User Story dalam Agile ditulis dalam format?",
            optionA: "Use case diagram teknis",
            optionB: 'Sebagai [peran], saya ingin [fitur], sehingga [manfaat]',
            optionC: "Kode pseudocode yang detail",
            optionD: "Diagram alur proses bisnis",
            correctAnswer: "B",
            explanation: "User Story ditulis dari perspektif pengguna dalam format: 'Sebagai [tipe pengguna], saya ingin [aksi/fitur], sehingga [nilai/manfaat yang didapat]'.",
          },
          {
            text: "Fase Requirements dalam SDLC bertujuan untuk?",
            optionA: "Menulis kode program",
            optionB: "Mengidentifikasi dan mendokumentasikan kebutuhan sistem dari stakeholder",
            optionC: "Menguji sistem yang sudah dibangun",
            optionD: "Merancang arsitektur database",
            correctAnswer: "B",
            explanation: "Fase Requirements bertujuan memahami dan mendokumentasikan apa yang dibutuhkan sistem, termasuk functional dan non-functional requirements dari stakeholder.",
          },
        ],
      },
      {
        name: "Testing & Desain Sistem",
        description: "Unit testing, integration testing, UML diagram",
        questions: [
          {
            text: "Unit testing adalah pengujian pada level?",
            optionA: "Keseluruhan sistem secara end-to-end",
            optionB: "Integrasi antar komponen",
            optionC: "Komponen atau fungsi terkecil secara individual",
            optionD: "Antarmuka pengguna",
            correctAnswer: "C",
            explanation: "Unit testing menguji komponen terkecil dari software (fungsi, method, atau class) secara individual dan terisolasi untuk memastikan setiap unit bekerja dengan benar.",
          },
          {
            text: "Apa yang dimaksud dengan regression testing?",
            optionA: "Pengujian performa sistem",
            optionB: "Pengujian untuk memastikan perubahan baru tidak merusak fungsi yang sebelumnya bekerja",
            optionC: "Pengujian dengan data yang salah",
            optionD: "Pengujian pada lingkungan produksi",
            correctAnswer: "B",
            explanation: "Regression testing dilakukan setelah ada perubahan kode untuk memastikan fungsionalitas yang sudah ada sebelumnya tidak rusak (tidak terjadi regresi).",
          },
          {
            text: "Use Case Diagram dalam UML digunakan untuk?",
            optionA: "Menggambarkan struktur kelas dan relasinya",
            optionB: "Menggambarkan interaksi antara aktor dan sistem",
            optionC: "Menggambarkan alur eksekusi program",
            optionD: "Menggambarkan struktur database",
            correctAnswer: "B",
            explanation: "Use Case Diagram menggambarkan fungsionalitas sistem dari perspektif pengguna (aktor) dan bagaimana mereka berinteraksi dengan sistem.",
          },
          {
            text: "Design pattern Singleton memastikan?",
            optionA: "Sebuah class memiliki tepat satu instance dan menyediakan akses global ke instance tersebut",
            optionB: "Setiap object memiliki salinannya sendiri",
            optionC: "Class tidak dapat diinstansiasi",
            optionD: "Semua method bersifat static",
            correctAnswer: "A",
            explanation: "Singleton pattern memastikan sebuah class hanya memiliki satu instance sepanjang siklus hidup aplikasi dan menyediakan titik akses global ke instance tersebut.",
          },
          {
            text: "Prinsip SOLID dalam pengembangan software, huruf S mengacu pada?",
            optionA: "Security Principle",
            optionB: "Single Responsibility Principle",
            optionC: "Simplicity Principle",
            optionD: "Synchronization Principle",
            correctAnswer: "B",
            explanation: "S dalam SOLID adalah Single Responsibility Principle: setiap class harus memiliki satu dan hanya satu alasan untuk berubah, artinya satu class bertanggung jawab pada satu fungsi.",
          },
        ],
      },
    ],
  },
];

async function main() {
  console.log("Menghapus semua data lama...");
  await prisma.quizAttempt.deleteMany({});
  await prisma.question.deleteMany({});
  await prisma.quiz.deleteMany({});
  await prisma.topic.deleteMany({});
  console.log("Data lama berhasil dihapus.");

  console.log("Mengisi data baru...");
  let totalTopics = 0;
  let totalQuizzes = 0;
  let totalQuestions = 0;

  for (const topic of data) {
    const createdTopic = await prisma.topic.create({
      data: {
        name: topic.name,
        description: topic.description,
        quizzes: {
          create: topic.quizzes.map((quiz) => ({
            name: quiz.name,
            description: quiz.description,
            questions: {
              create: quiz.questions,
            },
          })),
        },
      },
      include: {
        quizzes: {
          include: { _count: { select: { questions: true } } },
        },
      },
    });

    const quizCount = createdTopic.quizzes.length;
    const questionCount = createdTopic.quizzes.reduce((sum, q) => sum + q._count.questions, 0);
    
    totalTopics++;
    totalQuizzes += quizCount;
    totalQuestions += questionCount;

    console.log(`✓ ${createdTopic.name} — ${quizCount} kuis, ${questionCount} soal`);
  }

  console.log(`\nSelesai! Total: ${totalTopics} topik, ${totalQuizzes} kuis, ${totalQuestions} soal.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });